### ISSUE TITLE
Query error

### ISSUE THREAD

**Issue by SureFire-Richard** [intersystems/apps-rest#7] opened 2020-08-10 13:56 UTC
Implemented a Proxy on a simple data class.

A Postman request for a particular record from this class works great:
URL(fragment)
csp/sfonline/data/api/terms_base/64

Response:
{
    "%seriesCount": "1",
    "_id": "64",
    "ClientID": "290",
    "TermsCode": "50DepCOD",
    "ExternalLink": "80000008-1545415764",
    "Descr": "50% DEPOSIT",
    "TermsType": "N",
    "ShowOnShipper": false,
    "DepositPercentage": 50,
    "DiscAmt": 0,
    "DayIn1": 0,
    "MonthAdd1": 0,
    "DayOut1": 0,
    "DayIn2": 0,
    "MonthAdd2": 0,
    "DayOut2": 0,
    "DiscDays": 0,
    "NetDays": 0
}
 When I try to use an Action to pull a defined Query from the Data class using Postman:
URL(fragment):
csp/sfonline/data/api/terms_base/$byClientID?clientid=290

Response (last part):
<div id="content">
		<div class="content-container">
			<fieldset>
				<h2>406 - Client browser does not accept the MIME type of the requested page.</h2>
				<h3>The page you are looking for cannot be opened by your browser because it has a file name extension
					that your browser does not accept.</h3>
			</fieldset>
		</div>
	</div>

Attached are the data class and its Proxy that I am using (it is actually an Export XML of the 2 classes):

[CODE_TermsProxies.txt](https://github.com/intersystems/apps-rest/files/5051191/CODE_TermsProxies.txt)

**Comment by timleavitt** [comment] 2020-08-12 18:23
@SureFire-Richard - after further review, the issue is with the Action map - the model class should be a REST-adapted class, not just JSON-adapted; e.g.:
```
<actions xmlns="http://www.intersystems.com/apps/rest/action">
<action name="byClientID" target="class" method="GET"
modelClass="RestProxies.Lookups.Terms.Base" query="Lookups.Terms:ContactsForClientID">
<argument name="clientid" target="cClientOID" source="url"/>
</action>
</actions>
```

**Comment by timleavitt** [comment] 2020-08-12 18:25
Also, because the action is in RestProxies.Lookups.Terms.Base , you can omit the modelClass attribute entirely:

```
XData ActionMap [ XMLNamespace = "http://www.intersystems.com/apps/rest/action" ]
{
<actions xmlns="http://www.intersystems.com/apps/rest/action">
<action name="byClientID" target="class" method="GET" query="Lookups.Terms:ContactsForClientID">
<argument name="clientid" target="cClientOID" source="url"/>
</action>
</actions>
}
```

**Comment by timleavitt** [comment] 2020-08-12 21:02
Closing following verification in https://community.intersystems.com/post/appsrest-new-rest-framework-intersystems-iris#comment-130666

**Closed by timleavitt** 2020-08-12 21:02 UTC
